node {
  stage ("checkout") {
    sh 'ls'    
    checkout scm
    sh 'ls'
    }
  stage('Tag Branch') {  
    sshagent (credentials: ['gitkeynew']) {
      // get the last commit id from a repository you own
      // shortCommit = sh(returnStdout: true, script: "git log -n 1 --pretty=format:'%h'").trim()
      sh 'pwd'
      sh 'git log --oneline>log.txt'
      sh 'cat log.txt'
      sh 'echo "----current branch----"'
      sh 'git branch --show-current'
      //sh 'echo "${env.BRANCH_NAME}.${env.BUILD_NUMBER}"'
    }
  }
}
