pipeline {
    agent any
    stages {
        stage ("checkout") {
            steps{
                sh 'ls'    
                checkout scm
                sh 'ls'
            }
        }
        stage('build') {
            steps {
                sh 'ls'
            }
        }
        stage('starting') {
            environment { 
                DEBUG_TEXT = "${env.BRANCH_NAME}.${env.BUILD_ID}"
            }
            steps {
                sh 'echo $DEBUG_TEXT'
            }
        }
    }
}
